# -*- encoding=utf-8 -*-

import pickle, math, os, shutil
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import vtk, skfmm
from vtk.util.numpy_support import vtk_to_numpy

# own
import tools

# -----------------------------------------------------------------------------#

def sort_files(dict_user, dict_sample):
    '''
    Sort files generated by MOOSE to different directories
    '''
    os.rename('pf_out.e','vtk/pf_out.e')
    os.rename('pf.i','input/pf.i')
    j = 0
    j_str = index_to_str(j)
    j_total_str = index_to_str(dict_user['j_total'])
    filepath = Path('pf_other_'+j_str+'.pvtu')
    while filepath.exists():
        for i_proc in range(dict_user['n_proc']):
            os.rename('pf_other_'+j_str+'_'+str(i_proc)+'.vtu','vtk/pf_other_'+j_str+'_'+str(i_proc)+'.vtu')
            shutil.copyfile('vtk/pf_other_'+j_str+'_'+str(i_proc)+'.vtu','vtk/pf_'+j_total_str+'_'+str(i_proc)+'.vtu')
        os.rename('pf_other_'+j_str+'.pvtu','vtk/pf_other_'+j_str+'.pvtu')
        # write .pvtu to save all vtk
        file = open('vtk/pf_'+j_total_str+'.pvtu','w')
        file.write('''<?xml version="1.0"?>
        <VTKFile type="PUnstructuredGrid" version="0.1" byte_order="LittleEndian" header_type="UInt32" compressor="vtkZLibDataCompressor">
        \t<PUnstructuredGrid GhostLevel="1">
        \t\t<PPointData>
        \t\t\t<PDataArray type="Float64" Name="as"/>
        \t\t\t<PDataArray type="Float64" Name="kc"/>\n''')
        for i_eta in range(len(dict_sample['L_etai_map'])):
            file.write('''\t\t\t<PDataArray type="Float64" Name="eta'''+str(i_eta+1)+'''"/>\n''')
        file.write('''\t\t\t<PDataArray type="Float64" Name="c"/>
        \t\t</PPointData>
        \t\t<PCellData>
        \t\t\t<PDataArray type="Int32" Name="libmesh_elem_id"/>
        \t\t\t<PDataArray type="Int32" Name="subdomain_id"/>
        \t\t\t<PDataArray type="Int32" Name="processor_id"/>
        \t\t</PCellData>
        \t\t<PPoints>
        \t\t\t<PDataArray type="Float64" Name="Points" NumberOfComponents="3"/>
        \t\t</PPoints>''')
        line = ''
        for i_proc in range(dict_user['n_proc']):
            line = line + '''\t\t<Piece Source="pf_'''+j_total_str+'''_'''+str(i_proc)+'''.vtu"/>\n'''
        file.write(line)
        file.write('''\t</PUnstructuredGrid>
        </VTKFile>''')
        file.close()
        j = j + 1
        j_str = index_to_str(j)
        filepath = Path('pf_other_'+j_str+'.pvtu')
        dict_user['j_total'] = dict_user['j_total'] + 1
        j_total_str = index_to_str(dict_user['j_total'])
    return index_to_str(j-1)

# -----------------------------------------------------------------------------#

def index_to_str(j):
    '''
    Convert a integer into a string with the format XXX.
    '''
    if j < 10:
        return '00'+str(j)
    elif 10<=j and j<100:
        return '0'+str(j)
    else :
        return str(j)

# -----------------------------------------------------------------------------#

def read_vtk(dict_user, dict_sample, j_str):
    '''
    Read the last vtk files to obtain data from MOOSE.

    Do not work calling yade.
    '''
    if not dict_sample['Map_known']:
        L_XYZ = []
        L_L_i_XYZ = []

    # iterate on the proccessors used
    for i_proc in range(dict_user['n_proc']):
        print('processor',i_proc+1,'/',dict_user['n_proc'])

        # name of the file to load
        namefile = 'vtk/pf_other_'+j_str+'_'+str(i_proc)+'.vtu'

        # load a vtk file as input
        reader = vtk.vtkXMLUnstructuredGridReader()
        reader.SetFileName(namefile)
        reader.Update()

        # Grab a scalar from the vtk file
        nodes_vtk_array = reader.GetOutput().GetPoints().GetData()
        L_etai_vtk_array = []
        for i_grain in range(len(dict_sample['L_etai_map'])):
            L_etai_vtk_array.append(reader.GetOutput().GetPointData().GetArray("eta"+str(i_grain+1)))
        c_vtk_array = reader.GetOutput().GetPointData().GetArray("c")

        #Get the coordinates of the nodes and the scalar values
        nodes_array = vtk_to_numpy(nodes_vtk_array)
        L_etai_array = []
        for i_grain in range(len(dict_sample['L_etai_map'])):
            L_etai_array.append(vtk_to_numpy(L_etai_vtk_array[i_grain]))
        c_array = vtk_to_numpy(c_vtk_array)

        # map is not know
        if not dict_sample['Map_known']:
            # save the map
            L_i_XYZ = []
            # Must detect common zones between processors
            for i_XYZ in range(len(nodes_array)) :
                XYZ = nodes_array[i_XYZ]
                # Do not consider twice a point
                if list(XYZ) not in L_XYZ :
                    # search node in the mesh
                    L_search = list(abs(np.array(dict_sample['x_L']-list(XYZ)[0])))
                    i_x = L_search.index(min(L_search))
                    L_search = list(abs(np.array(dict_sample['y_L']-list(XYZ)[1])))
                    i_y = L_search.index(min(L_search))
                    L_search = list(abs(np.array(dict_sample['z_L']-list(XYZ)[2])))
                    i_z = L_search.index(min(L_search))
                    # save map
                    L_XYZ.append(list(XYZ))
                    L_i_XYZ.append([i_x, i_y, i_z])
                    # rewrite map
                    for i_grain in range(len(dict_sample['L_etai_map'])):
                        dict_sample['L_etai_map'][i_grain][i_x, i_y, i_z] = L_etai_array[i_grain][i_XYZ]
                    dict_sample['c_map'][i_x, i_y, i_z] = c_array[i_XYZ]
                else :
                    L_i_XYZ.append(None)
            # Here the algorithm can be help as the mapping is known
            L_L_i_XYZ.append(L_i_XYZ)

        # map is known
        else :
            # iterate on data
            for i_XYZ in range(len(nodes_array)) :
                # read
                if dict_sample['L_L_i_XYZ_used'][i_proc][i_XYZ] != None :
                    i_x = dict_sample['L_L_i_XYZ_used'][i_proc][i_XYZ][0]
                    i_y = dict_sample['L_L_i_XYZ_used'][i_proc][i_XYZ][1]
                    i_z = dict_sample['L_L_i_XYZ_used'][i_proc][i_XYZ][2]
                    # rewrite map
                    for i_grain in range(len(dict_sample['L_etai_map'])):
                        dict_sample['L_etai_map'][i_grain][i_x, i_y, i_z] = L_etai_array[i_grain][i_XYZ]
                    dict_sample['c_map'][i_x, i_y, i_z] = c_array[i_XYZ]
    
    if not dict_sample['Map_known']:
        # the map is known
        dict_sample['Map_known'] = True
        dict_sample['L_L_i_XYZ_used'] = L_L_i_XYZ

# -----------------------------------------------------------------------------#

def compute_levelset(dict_user, dict_sample):
    '''
    From a phase map, compute level set function.
    '''
    L_sdf_i_map = []
    # iterate on the phase variable
    for i_grain in range(len(dict_sample['L_etai_map'])):
        # compute binary map
        bin_i_map = np.array(np.zeros((dict_user['n_mesh_x'], dict_user['n_mesh_y'], dict_user['n_mesh_z'])))
        # iteration on x
        for i_x in range(len(dict_sample['x_L'])):
            # iteration on y
            for i_y in range(len(dict_sample['y_L'])):
                # iteration on z
                for i_z in range(len(dict_sample['z_L'])):
                    # grain 1
                    if dict_sample['L_etai_map'][i_grain][i_x, i_y, i_z] > 0.5:
                        bin_i_map[i_x, i_y, i_z] = 1
                    else :
                        bin_i_map[i_x, i_y, i_z] = -1
        # compute signed distance function
        sdf_i_map = -skfmm.distance(bin_i_map, dx=np.array([dict_sample['x_L'][1]-dict_sample['x_L'][0],\
                                                            dict_sample['y_L'][1]-dict_sample['y_L'][0],\
                                                            dict_sample['z_L'][1]-dict_sample['z_L'][0]]))
        # save
        L_sdf_i_map.append(sdf_i_map)

    # save data
    dict_save = {
    'L_x': dict_sample['x_L'],
    'L_y': dict_sample['y_L'],
    'L_z': dict_sample['z_L'],
    'L_sdf_i_map': L_sdf_i_map
    }
    with open('data/level_sets.data', 'wb') as handle:
        pickle.dump(dict_save, handle, protocol=pickle.HIGHEST_PROTOCOL)


